In [5]:
import numpy as np

In [6]:
# TASK 33
images = np.array([
    [-1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1],
    [1, -1, 1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1],
    [1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1],
])
labels = np.array([
    [-1, -1, 1],
    [-1, 1, -1],
    [-1, 1, 1]
])

# TASK 36
images = np.array([
    [-1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1],
    [1, -1, 1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1],
    [1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1],
])
labels = np.array([
    [-1, 1],
    [1, -1],
    [1, 1]
])

In [7]:
print('ОБУЧЕНИЕ СЕТИ ПО ПРАВИЛУ ХЕББА')
w = 0
for i, (image, label) in enumerate(zip(images, labels)):
    print(f'ОБРАЗ {i + 1}')
    image_matrix = np.expand_dims(image, axis=0)
    label_matrix = np.expand_dims(label, axis=0)
    w += image_matrix.T @ label_matrix
    print(f'W[{i}] +')
    print(np.array_str(image_matrix.T, suppress_small=True))
    print('*')
    print(np.array_str(label_matrix, suppress_small=True))
    print('=')
    print(np.array_str(w, suppress_small=True), f'= W[{i + 1}]')
    print('-' * 10)
print('ФИНАЛЬНЫЕ ВЕСА')
print(np.array_str(w, suppress_small=True))

ОБУЧЕНИЕ СЕТИ ПО ПРАВИЛУ ХЕББА
ОБРАЗ 1
W[0] +
[[-1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]
 [ 1]]
*
[[-1  1]]
=
[[ 1 -1]
 [-1  1]
 [ 1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1  1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [-1  1]] = W[1]
----------
ОБРАЗ 2
W[1] +
[[ 1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [ 1]]
*
[[ 1 -1]]
=
[[ 2 -2]
 [-2  2]
 [ 2 -2]
 [ 2 -2]
 [ 0  0]
 [ 0  0]
 [-2  2]
 [ 0  0]
 [-2  2]
 [ 0  0]
 [ 2 -2]
 [ 2 -2]
 [ 2 -2]
 [ 0  0]
 [ 0  0]] = W[2]
----------
ОБРАЗ 3
W[2] +
[[ 1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]]
*
[[1 1]]
=
[[ 3 -1]
 [-3  1]
 [ 1 -3]
 [ 1 -3]
 [ 1  1]
 [ 1  1]
 [-3  1]
 [ 1  1]
 [-3  1]
 [ 1  1]
 [ 3 -1]
 [ 3 -1]
 [ 3 -1]
 [ 1  1]
 [ 1  1]] = W[3]
----------
ФИНАЛЬНЫЕ ВЕСА
[[ 3 -1]
 [-3  1]
 [ 1 -3]
 [ 1 -3]
 [ 1  1]
 [ 1  1]
 [-3  1]
 [ 1  1]
 [-3  1]
 [ 1  1]
 [ 3 -1]
 [ 3 -1]
 [ 3 -1]
 [ 1  1]
 [ 1  1]

In [8]:
def modified_sign(current, prev):
    new = np.sign(current)
    not_updated_mask = np.where(new == 0)
    new[not_updated_mask] = prev[not_updated_mask]
    return new

# TASK 33
prediction_label = np.array([1, -1, -1])

# TASK 36
prediction_label = np.array([-1, -1])


np.expand_dims(prediction_label, axis=1)
iters = 0
prev_input = modified_sign(prediction_label @ w.T, np.zeros_like(prediction_label @ w.T))
prev_output = prediction_label
print(f'СОСТОЯНИЕ {iters}')
print(np.array_str(prediction_label, suppress_small=True))
print('*')
print(np.array_str(w.T, suppress_small=True))
print('=')
print(np.array_str(prediction_label @ w.T, suppress_small=True))
print('=(С МОДИФИЦИРОВАННОЙ ФУНКЦИЕЙ ЗНАКА)=')
print(np.array_str(prev_input, suppress_small=True), f'= X[{iters}]')
print(np.array_str(prev_output, suppress_small=True), f'= Y[{iters}]')
while iters <= 100:
    iters += 1
    print(f'СОСТОЯНИЕ {iters}')

    # INPUT LAYER STATE
    print('НОВОЕ СОСТОЯНИЕ ПЕРВОГО СЛОЯ')
    print(np.array_str(prev_output, suppress_small=True))
    print('*')
    print(np.array_str(w.T, suppress_small=True))
    print('=')
    print(np.array_str(prev_output @ w.T, suppress_small=True))
    print('=(С МОДИФИЦИРОВАННОЙ ФУНКЦИЕЙ ЗНАКА)=')
    new_input = modified_sign(prev_output @ w.T, prev_input)
    print(np.array_str(new_input, suppress_small=True), f'= X[{iters}]')

    # OUTPUT LAYER STATE
    print('НОВОЕ СОСТОЯНИЕ ВТОРОГО СЛОЯ')
    print(np.array_str(prev_input, suppress_small=True))
    print('*')
    print(np.array_str(w, suppress_small=True))
    print('=')
    print(np.array_str(prev_input @ w, suppress_small=True))
    print('=(С МОДИФИЦИРОВАННОЙ ФУНКЦИЕЙ ЗНАКА)=')
    new_output = modified_sign(prev_input @ w, prev_output)
    print(np.array_str(new_output, suppress_small=True), f'= Y[{iters}]')

    # RELAXATION CONDITION
    print('ПРОВЕРКА РЕЛАКСАЦИИ')
    output_equality = np.array_equal(prev_output, new_output)
    input_equality = np.array_equal(prev_input, new_input)
    if output_equality and input_equality:
        print(f'Y[{iters - 1}] = Y[{iters}]')
        print(f'X[{iters - 1}] = X[{iters}]')
        print(f'СЕТЬ ДОСТИГЛА РЕЛАКСАЦИИ НА ИТЕРАЦИИ {iters}')
        break
    else:        
        print(f'X[{iters - 1}] {"=" if input_equality else "!="} X[{iters}]')
        print(f'Y[{iters - 1}] {"=" if output_equality else "!="} Y[{iters}]')
     

СОСТОЯНИЕ 0
[-1 -1]
*
[[ 3 -3  1  1  1  1 -3  1 -3  1  3  3  3  1  1]
 [-1  1 -3 -3  1  1  1  1  1  1 -1 -1 -1  1  1]]
=
[-2  2  2  2 -2 -2  2 -2  2 -2 -2 -2 -2 -2 -2]
=(С МОДИФИЦИРОВАННОЙ ФУНКЦИЕЙ ЗНАКА)=
[-1  1  1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1] = X[0]
[-1 -1] = Y[0]
СОСТОЯНИЕ 1
НОВОЕ СОСТОЯНИЕ ПЕРВОГО СЛОЯ
[-1 -1]
*
[[ 3 -3  1  1  1  1 -3  1 -3  1  3  3  3  1  1]
 [-1  1 -3 -3  1  1  1  1  1  1 -1 -1 -1  1  1]]
=
[-2  2  2  2 -2 -2  2 -2  2 -2 -2 -2 -2 -2 -2]
=(С МОДИФИЦИРОВАННОЙ ФУНКЦИЕЙ ЗНАКА)=
[-1  1  1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1] = X[1]
НОВОЕ СОСТОЯНИЕ ВТОРОГО СЛОЯ
[-1  1  1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1]
*
[[ 3 -1]
 [-3  1]
 [ 1 -3]
 [ 1 -3]
 [ 1  1]
 [ 1  1]
 [-3  1]
 [ 1  1]
 [-3  1]
 [ 1  1]
 [ 3 -1]
 [ 3 -1]
 [ 3 -1]
 [ 1  1]
 [ 1  1]]
=
[-25  -5]
=(С МОДИФИЦИРОВАННОЙ ФУНКЦИЕЙ ЗНАКА)=
[-1 -1] = Y[1]
ПРОВЕРКА РЕЛАКСАЦИИ
Y[0] = Y[1]
X[0] = X[1]
СЕТЬ ДОСТИГЛА РЕЛАКСАЦИИ НА ИТЕРАЦИИ 1
