In [4]:
import numpy as np
from lstm2 import (
    LSTMModel,
    fibonacci_generator,
    one_by_n_generator,
    plus_one_minus_one_generator,
    squared_generator,
    half_generator,
    arithmetic_progression,
    create_sliding_window_batches,
    one_half_generator,    
    mape
)
import plotly.graph_objects as go

In [5]:
# seq_length = 10
# window_size = 5
# batch_size = 2
# hidden_size = 4
# output_size = 3

# sequence = list(fibonacci_generator(seq_length))
# X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)
# X_train, y_train = X[0:int(len(X) * 0.8)], y[0:int(len(X) * 0.8)][-1]
# X_test, y_test = X[int(len(X) * 0.8):], y[int(len(X) * 0.8):][-1]

# verbosity = 1000

# max_mape = 1e-3
# learn_until_meet_mape = True

# model = GRUModel(window_size, hidden_size, output_size)

# # Параметры обучения
# lr = 1e-4
# epochs = 5000

# model.train(X_train, y_train, lr, epochs,
#             True, max_mape, verbosity)
# Проверим результат после обучения
# y_pred, _, _ = model.forward(X_train)
# print("Предсказание после обучения:\n", y_pred)
# print("Истинное значение:\n", y_train)
# print(f"MAPE: {mape(y_train, y_pred) * 100:.4f}%")

# print('TEST')
# y_pred, _, _ = model.forward(X_test)
# print("Предсказания на тестовой выборке:\n", y_pred)
# print("Истинное значение на тестовой выборке:\n", y_test)
# print(f"MAPE: {mape(y_test, y_pred) * 100:.4f}%")  

In [17]:
experiments_amount = 5
# epochs = np.linspace(1000, 35000, endpoint=True, num=10).astype(np.int32).tolist()
epochs = list(range(100, 2100, 100))

# np.random.seed(12345)

all_mapes = []
mapes_mean = []

all_epochs: list[int] = []

seq_length = 20
window_size = 5
batch_size = 2
hidden_size = 10
output_size = 3

verbosity = 100000
lr = 1e-4

sequence = list(arithmetic_progression(seq_length, a0=1, d=1))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

for max_epochs in epochs:    

    # Training network for five times
    mapes_sum = 0    
    for _ in range(experiments_amount):              
        
        network = LSTMModel(input_size=window_size, hidden_size=hidden_size,
                           output_size=output_size)
        _, _mape = network.train(x=X, y=y, lr=lr, max_epochs=max_epochs, verbosity=verbosity)
        all_epochs.append(max_epochs)
        mapes_sum += _mape        
        all_mapes.append(_mape)    

    # Average mape for epochs amount
    mapes_mean.append(mapes_sum / experiments_amount)

TRAINING FINISHED
Epoch 100/100, Loss: 130.652030
MAPE: 0.820560
TRAINING FINISHED
Epoch 100/100, Loss: 167.648488
MAPE: 0.925938
TRAINING FINISHED
Epoch 100/100, Loss: 96.537978
MAPE: 0.704059
TRAINING FINISHED
Epoch 100/100, Loss: 130.026692
MAPE: 0.824388
TRAINING FINISHED
Epoch 100/100, Loss: 152.437521
MAPE: 0.887367
TRAINING FINISHED
Epoch 200/200, Loss: 69.868951
MAPE: 0.594927
TRAINING FINISHED
Epoch 200/200, Loss: 119.207397
MAPE: 0.781790
TRAINING FINISHED
Epoch 200/200, Loss: 91.764338
MAPE: 0.688739
TRAINING FINISHED
Epoch 200/200, Loss: 140.589988
MAPE: 0.841248
TRAINING FINISHED
Epoch 200/200, Loss: 105.769011
MAPE: 0.741651
TRAINING FINISHED
Epoch 300/300, Loss: 51.415716
MAPE: 0.512712
TRAINING FINISHED
Epoch 300/300, Loss: 58.008942
MAPE: 0.540236
TRAINING FINISHED
Epoch 300/300, Loss: 25.979546
MAPE: 0.368854
TRAINING FINISHED
Epoch 300/300, Loss: 101.968916
MAPE: 0.710995
TRAINING FINISHED
Epoch 300/300, Loss: 56.419472
MAPE: 0.534478
TRAINING FINISHED
Epoch 400/400,

In [18]:
# Plotting results for training epochs amount
fig = go.Figure()
fig.add_trace(
    go.Scatter(x=all_epochs, y=all_mapes,
               name='Все наблюдения', mode='markers')
)
fig.add_trace(
    go.Scatter(x=epochs, y=mapes_mean,
               name='Средние значения', mode='lines+markers')
)
fig.update_layout(
    title='Зависимость средней абсолютной ошибки от количества итераций обучения',
    font=dict(size=20),
    xaxis=dict(title='Количество итераций обучения'),
    yaxis=dict(title='Средняя абсолютная ошибка'),
    width=1280,
    height=720
)
fig.show()

In [21]:
experiments_amount = 5
# epochs = np.linspace(1000, 35000, endpoint=True, num=10).astype(np.int32).tolist()
hidden_sizes = list(range(2, 22, 2))

# np.random.seed(12345)

all_mapes = []
mapes_mean = []

all_sizes: list[int] = []

seq_length = 20
window_size = 5
batch_size = 2
output_size = 3

verbosity = 100000
lr = 1e-4
max_epochs = 250

sequence = list(arithmetic_progression(seq_length, a0=1, d=1))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)
y = y

for size in hidden_sizes:    

    # Training network for five times
    mapes_sum = 0    
    for _ in range(experiments_amount):              
        
        network = LSTMModel(input_size=window_size, hidden_size=size,
                           output_size=output_size)
        _, _mape = network.train(x=X, y=y, lr=lr, max_epochs=max_epochs, verbosity=verbosity)
        all_sizes.append(size)
        mapes_sum += _mape        
        all_mapes.append(_mape)    

    # Average mape for epochs amount
    mapes_mean.append(mapes_sum / experiments_amount)

TRAINING FINISHED
Epoch 250/250, Loss: 182.598996
MAPE: 0.952731
TRAINING FINISHED
Epoch 250/250, Loss: 148.287347
MAPE: 0.871074
TRAINING FINISHED
Epoch 250/250, Loss: 148.999925
MAPE: 0.858446
TRAINING FINISHED
Epoch 250/250, Loss: 190.615791
MAPE: 0.982777
TRAINING FINISHED
Epoch 250/250, Loss: 142.939457
MAPE: 0.832868
TRAINING FINISHED
Epoch 250/250, Loss: 140.302389
MAPE: 0.843254
TRAINING FINISHED
Epoch 250/250, Loss: 100.971211
MAPE: 0.711467
TRAINING FINISHED
Epoch 250/250, Loss: 124.490938
MAPE: 0.793609
TRAINING FINISHED
Epoch 250/250, Loss: 99.946511
MAPE: 0.700935
TRAINING FINISHED
Epoch 250/250, Loss: 149.848308
MAPE: 0.869503
TRAINING FINISHED
Epoch 250/250, Loss: 68.130129
MAPE: 0.582356
TRAINING FINISHED
Epoch 250/250, Loss: 139.484267
MAPE: 0.836633
TRAINING FINISHED
Epoch 250/250, Loss: 137.191504
MAPE: 0.831613
TRAINING FINISHED
Epoch 250/250, Loss: 183.145547
MAPE: 0.963793
TRAINING FINISHED
Epoch 250/250, Loss: 151.621912
MAPE: 0.876404
TRAINING FINISHED
Epoch 250

In [22]:
# Plotting results for training epochs amount
fig = go.Figure()
fig.add_trace(
    go.Scatter(x=all_sizes, y=all_mapes,
               name='Все наблюдения', mode='markers')
)
fig.add_trace(
    go.Scatter(x=hidden_sizes, y=mapes_mean,
               name='Средние значения', mode='lines+markers')
)
fig.update_layout(
    title='Зависимость средней абсолютной ошибки от<br>количества нейронов на скрытом слое',
    font=dict(size=20),
    xaxis=dict(title='Количество нейронов на скрытом слое'),
    yaxis=dict(title='Средняя абсолютная ошибка'),
    width=1280,
    height=720
)
fig.show()

In [ ]:
# MAPE relation with sliding window
experiments_amount = 5
# epochs = np.linspace(1000, 35000, endpoint=True, num=10).astype(np.int32).tolist()


all_mapes = []
mapes_mean = []

all_sizes: list[int] = []

seq_length = 50
window_sizes = list(range(1, seq_length // 2))
hidden_size = 10
batch_size = 2
output_size = 3

verbosity = 100000
max_mape = 1e-3
learn_until_meet_mape = True
lr = 1e-4
max_epochs = 1000

sequence = list(arithmetic_progression(seq_length, a0=1, d=1))

for size in window_sizes:
    X, y = create_sliding_window_batches(sequence, size, batch_size, output_size)    

    # Training network for five times
    mapes_sum = 0    
    for _ in range(experiments_amount):              
        
        network = LSTMModel(input_size=size, hidden_size=hidden_size,
                           output_size=output_size)
        _, _mape = network.train(x=X, y=y, lr=lr, max_epochs=max_epochs, verbosity=verbosity)
        all_sizes.append(size)
        mapes_sum += _mape        
        all_mapes.append(_mape)    

    # Average mape for epochs amount
    mapes_mean.append(mapes_sum / experiments_amount)

TRAINING FINISHED
Epoch 1000/1000, Loss: 26.459103
MAPE: 0.277024
TRAINING FINISHED
Epoch 1000/1000, Loss: 27.434781
MAPE: 0.267282
TRAINING FINISHED
Epoch 1000/1000, Loss: 31.542667
MAPE: 0.291978
TRAINING FINISHED
Epoch 1000/1000, Loss: 29.980128
MAPE: 0.277767
TRAINING FINISHED
Epoch 1000/1000, Loss: 27.642514
MAPE: 0.285426
TRAINING FINISHED
Epoch 1000/1000, Loss: 23.198698
MAPE: 0.249281
TRAINING FINISHED
Epoch 1000/1000, Loss: 26.955759
MAPE: 0.253368
TRAINING FINISHED
Epoch 1000/1000, Loss: 25.680835
MAPE: 0.262120
TRAINING FINISHED
Epoch 1000/1000, Loss: 29.290951
MAPE: 0.268917
TRAINING FINISHED
Epoch 1000/1000, Loss: 21.375383
MAPE: 0.242705
TRAINING FINISHED
Epoch 1000/1000, Loss: 21.018603
MAPE: 0.225124
TRAINING FINISHED
Epoch 1000/1000, Loss: 19.101579
MAPE: 0.225380
TRAINING FINISHED
Epoch 1000/1000, Loss: 14.426221
MAPE: 0.180234
TRAINING FINISHED
Epoch 1000/1000, Loss: 17.166780
MAPE: 0.211155
TRAINING FINISHED
Epoch 1000/1000, Loss: 13.617660
MAPE: 0.179000
TRAINING F

In [29]:
# Plotting results
fig = go.Figure()
fig.add_trace(
    go.Scatter(x=all_sizes, y=all_mapes,
               name='Все наблюдения', mode='markers')
)
fig.add_trace(
    go.Scatter(x=window_sizes, y=mapes_mean,
               name='Средние значения', mode='lines+markers')
)
fig.update_layout(
    title='Зависимость средней абсолютной ошибки от<br>размера скользящего окна',
    font=dict(size=20),
    xaxis=dict(title='Размер скользящего окна'),
    yaxis=dict(title='Средняя абсолютная ошибка'),
    width=1280,
    height=720
)
fig.show()

In [12]:
# Настройки эксперимента
experiments_amount = 5
seq_length = 10
window_size = 3
batch_size = 2
hidden_size = 10
output_size = 3
max_epochs = 2000
verbosity = 100000
lr = 1e-4

# Словарь с генераторами
sequence_generators = {
    "1, 1, 2, 3, 5, 8,...": lambda n: list(fibonacci_generator(n)),
    "1, 4, 9, 16,...": lambda n: list(squared_generator(n)),
    "1, 2, 3, 4, 5,...": lambda n: list(arithmetic_progression(n, a0=1, d=1)),    
    "1, 0.5 ,0.(3), 0.25, 0.2,...": lambda n: list(one_by_n_generator(n)),
    "1, -1, 1, -1,...": lambda n: list(plus_one_minus_one_generator(n)),
    "1, 0.5, 1, 0.5, 0.5, 1,...": lambda n: list(one_half_generator(n)),
}

all_mapes = []
mapes_mean = []
all_sequences = []

# Тренировка для каждой последовательности
for seq_name, seq_generator in sequence_generators.items():
    sequence = seq_generator(seq_length)
    print(sequence)
    X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

    mapes_sum = 0
    for _ in range(experiments_amount):
        network = LSTMModel(input_size=window_size, hidden_size=hidden_size, output_size=output_size)
        _, _mape = network.train(x=X, y=y, lr=lr, max_epochs=max_epochs, verbosity=verbosity)
        all_sequences.append(seq_name)
        all_mapes.append(_mape)
        mapes_sum += _mape

    mapes_mean.append(mapes_sum / experiments_amount)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
TRAINING FINISHED
Epoch 2000/2000, Loss: 10.364070
MAPE: 0.232588
TRAINING FINISHED
Epoch 2000/2000, Loss: 9.432886
MAPE: 0.227119
TRAINING FINISHED
Epoch 2000/2000, Loss: 6.726360
MAPE: 0.200316
TRAINING FINISHED
Epoch 2000/2000, Loss: 12.465468
MAPE: 0.228770
TRAINING FINISHED
Epoch 2000/2000, Loss: 13.807684
MAPE: 0.231440
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
TRAINING FINISHED
Epoch 2000/2000, Loss: 8.203199
MAPE: 0.057872
TRAINING FINISHED
Epoch 2000/2000, Loss: 12.226541
MAPE: 0.058663
TRAINING FINISHED
Epoch 2000/2000, Loss: 9.054044
MAPE: 0.056231
TRAINING FINISHED
Epoch 2000/2000, Loss: 12.315123
MAPE: 0.065812
TRAINING FINISHED
Epoch 2000/2000, Loss: 52.697611
MAPE: 0.107278
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
TRAINING FINISHED
Epoch 2000/2000, Loss: 1.386314
MAPE: 0.155626
TRAINING FINISHED
Epoch 2000/2000, Loss: 1.207720
MAPE: 0.143091
TRAINING FINISHED
Epoch 2000/2000, Loss: 1.395904
MAPE: 0.166395
TRAINING FINISHED
Epoch 2000/2000, Loss: 1.0

In [13]:
# Построение графика
fig = go.Figure()
fig.add_trace(
    go.Scatter(x=all_sequences, y=all_mapes, name="Все наблюдения", mode="markers")
)
fig.add_trace(
    go.Scatter(x=list(sequence_generators.keys()), y=mapes_mean, name="Средние значения", mode="markers")
)
fig.update_layout(
    title="Зависимость средней абсолютной ошибки<br>от вида последовательности",
    font=dict(size=20),
    xaxis=dict(title="Вид последовательности"),
    yaxis=dict(title="Средняя абсолютная ошибка"),
    width=1280,
    height=720
)
fig.show()

In [14]:
# Arithmetic
seq_length = 20
window_size = 5
batch_size = 2
hidden_size = 10
output_size = 3

sequence = list(arithmetic_progression(seq_length, 1, 1))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

verbosity = 5000
model = LSTMModel(window_size, hidden_size, output_size)

# Параметры обучения
lr = 1e-3
epochs = 2000

model.train(x=X, y=y, lr=lr, max_epochs=epochs, verbosity=verbosity)

print('TEST')
y_pred, _, _ = model.forward(X)
print("Предсказания на тестовой выборке:\n", y_pred[-1][-1])
print("Истинное значение на тестовой выборке:\n", y[-1][-1])
print(f"MAPE: {mape(y[-1][-1], y_pred[-1][-1]) * 100:.4f}%")  

TRAINING FINISHED
Epoch 2000/2000, Loss: 0.083103
MAPE: 0.020253
TEST


ValueError: too many values to unpack (expected 3)

In [10]:
# Fibonacci
seq_length = 15
window_size = 5
batch_size = 2
hidden_size = 10
output_size = 3

sequence = list(fibonacci_generator(seq_length))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

verbosity = 5000
model = LSTMModel(window_size, hidden_size, output_size)

# Параметры обучения
lr = 1e-3
epochs = 2000

model.train(x=X, y=y, lr=lr, max_epochs=epochs, verbosity=verbosity)

print('TEST')
y_pred, _, _ = model.forward(X)
print("Предсказания на тестовой выборке:\n", y_pred[-1][-1])
print("Истинное значение на тестовой выборке:\n", y[-1][-1])
print(f"MAPE: {mape(y[-1][-1], y_pred[-1][-1]) * 100:.4f}%")

TRAINING FINISHED
Epoch 2000/2000, Loss: 401.406563
MAPE: 0.249506
TEST
Предсказания на тестовой выборке:
 [124.3206073  201.14490545 325.4805035 ]
Истинное значение на тестовой выборке:
 [144 233 377]
MAPE: 13.6679%


In [11]:
# 1 / n
seq_length = 20
window_size = 5
batch_size = 2
hidden_size = 10
output_size = 3

sequence = list(one_by_n_generator(seq_length))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

verbosity = 5000
model = LSTMModel(window_size, hidden_size, output_size)

# Параметры обучения
lr = 1e-3
epochs = 2000

model.train(x=X, y=y, lr=lr, max_epochs=epochs, verbosity=verbosity)

print('TEST')
y_pred, _, _ = model.forward(X)
print("Предсказания на тестовой выборке:\n", y_pred[-1][-1])
print("Истинное значение на тестовой выборке:\n", y[-1][-1])
print(f"MAPE: {mape(y[-1][-1], y_pred[-1][-1]) * 100:.4f}%")

TRAINING FINISHED
Epoch 2000/2000, Loss: 0.001185
MAPE: 0.249061
TEST
Предсказания на тестовой выборке:
 [0.06865588 0.0529477  0.07845942]
Истинное значение на тестовой выборке:
 [0.05555556 0.05263158 0.05      ]
MAPE: 27.0334%


In [12]:
# 1, -1, 1, -1, ...
seq_length = 20
window_size = 5
batch_size = 2
hidden_size = 10
output_size = 3

sequence = list(plus_one_minus_one_generator(seq_length))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

verbosity = 2000
model = LSTMModel(window_size, hidden_size, output_size)

# Параметры обучения
lr = 1e-3
epochs = 2000

model.train(x=X, y=y, lr=lr, max_epochs=epochs, verbosity=verbosity)

print('TEST')
y_pred, _, _ = model.forward(X)
print("Предсказания на тестовой выборке:\n", y_pred[-1][-1])
print("Истинное значение на тестовой выборке:\n", y[-1][-1])
print(f"MAPE: {mape(y[-1][-1], y_pred[-1][-1]) * 100:.4f}%") 

Epoch 2000/2000, Loss: 0.083253
MAPE: 0.198552
TRAINING FINISHED
Epoch 2000/2000, Loss: 0.083253
MAPE: 0.198552
TEST
Предсказания на тестовой выборке:
 [-0.29187779  0.14308726 -0.24763119]
Истинное значение на тестовой выборке:
 [-1  1 -1]
MAPE: 77.2468%


In [13]:
# n ** 2
seq_length = 10
window_size = 3
batch_size = 2
hidden_size = 10
output_size = 3

sequence = list(squared_generator(seq_length))
X, y = create_sliding_window_batches(sequence, window_size, batch_size, output_size)

verbosity = 5000
model = LSTMModel(window_size, hidden_size, output_size)

# Параметры обучения
lr = 1e-3
epochs = 2000

model.train(x=X, y=y, lr=lr, max_epochs=epochs, verbosity=verbosity)

print('TEST')
y_pred, _, _ = model.forward(X)
print("Предсказания на тестовой выборке:\n", y_pred[-1][-1])
print("Истинное значение на тестовой выборке:\n", y[-1][-1])
print(f"MAPE: {mape(y[-1][-1], y_pred[-1][-1]) * 100:.4f}%") 

TRAINING FINISHED
Epoch 2000/2000, Loss: 0.303113
MAPE: 0.010584
TEST
Предсказания на тестовой выборке:
 [ 64.65079107  81.64464169 100.35348175]
Истинное значение на тестовой выборке:
 [ 64  81 100]
MAPE: 0.7221%
